### PR TITLE
Remove exec bit

### LINKED ISSUE #235: Changie create files with executable bit
**Description**
Changie create files with executable bit (`init`, `new` and other stage/commands).

**Reproduction Steps**
TBD

**What happened**
Files created with executable bit

**Expected behavior**
There is no exec bit on text files

**Additional context**

### PR DESCRIPTION
**Pull request by GennadySpb**
Closes #235

**Check the following**
- [ ] Keep 100% code coverage
- [ ] Be properly formatted
- [ ] Have no linting errors
- [ ] Documentation changes are included
- [ ] Include a change file if expected

**Additional context**
Any additional info that might help get your pull request merged.

### CODE REVIEW

File: core/config.go [hunk 1]
```diff
@@ -11,6 +11,8 @@ import (
 )
 
 const configEnvVar = "CHANGIE_CONFIG_PATH"
+const DefaultFileMode os.FileMode = 0644
+const DefaultDirMode os.FileMode = 0755
```
Comment (miniscruff) [inline core/config.go:15]:
```suggestion
const CreateFileMode os.FileMode = 0644
const CreateDirMode os.FileMode = 0755
```
I think naming these after what we are doing makes more sense then default, as to me default implies there are other options which there are not.

**Review by miniscruff — CHANGES_REQUESTED** [review]
Couple wording changes but looks great, thanks

File: core/config.go [hunk 2]
```diff
@@ -94,7 +96,7 @@ func (c Config) ChangeFormatForKind(label string) string {
 // Save will save the config as a yaml file to the default path
 func (c Config) Save(wf shared.WriteFiler) error {
 	bs, _ := yaml.Marshal(&c)
-	return wf(ConfigPaths[0], bs, os.ModePerm)
+	return wf(ConfigPaths[0], bs, DefaultFileMode)
```
Comment (miniscruff) [inline core/config.go:99]:
```suggestion
	return wf(ConfigPaths[0], bs, CreateFileMode)
```

File: core/utils_test.go [hunk 3]
```diff
@@ -24,7 +24,7 @@ var _ = Describe("Utils", func() {
 		_, err = rootFile.WriteString("root")
 		Expect(err).To(BeNil())
 
-		err = afs.WriteFile("append.txt", []byte(" append"), os.ModePerm)
+		err = afs.WriteFile("append.txt", []byte(" append"), DefaultFileMode)
```
Comment (miniscruff) [inline core/utils_test.go:27]:
```suggestion
		err = afs.WriteFile("append.txt", []byte(" append"), CreateFileMode)
```

File: cmd/merge_test.go [hunk 4]
```diff
@@ -269,13 +268,13 @@ first version`
...
 		headerContents := []byte("a simple header\n")
-		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
 		Expect(err).To(BeNil())
 
 		onePath := filepath.Join("news", "v0.1.0.md")
 
 		oneChanges := []byte("first version")
-		err = afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err = afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:277]:
```suggestion
		err = afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 5]
```diff
@@ -269,13 +268,13 @@ first version`
 		saveAndCheckConfig()
 
 		headerContents := []byte("a simple header\n")
-		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:271]:
```suggestion
		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 6]
```diff
@@ -242,12 +241,12 @@ first version`
...
 		Expect(err).To(BeNil())
 
 		onePath := filepath.Join("news", "v0.1.0.md")
 		oneChanges := []byte("first version")
-		err = afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err = afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:249]:
```suggestion
		err = afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 7]
```diff
@@ -242,12 +241,12 @@ first version`
 		badError := errors.New("bad write string")
 
 		headerContents := []byte("a simple header\n")
-		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:244]:
```suggestion
		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 8]
```diff
@@ -223,13 +222,13 @@ first version`
...
 		Expect(err).To(BeNil())
 
 		onePath := filepath.Join("news", "v0.1.0.md")
 
 		oneChanges := []byte("first version")
-		err = afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err = afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:231]:
```suggestion
		err = afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 9]
```diff
@@ -223,13 +222,13 @@ first version`
 
 		// we need a header and at least one version
 		headerContents := []byte("a simple header\n")
-		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:225]:
```suggestion
		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 10]
```diff
@@ -197,7 +196,7 @@ first version`
 		// need at least one change to exist
 		onePath := filepath.Join("news", "v0.1.0.md")
 		oneChanges := []byte("first version")
-		err := afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err := afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:199]:
```suggestion
		err := afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 11]
```diff
@@ -133,7 +132,7 @@ first version`
 		saveAndCheckConfig()
 
 		headerContents := []byte("a simple header\n")
-		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:135]:
```suggestion
		err := afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 12]
```diff
@@ -103,15 +102,15 @@ first version`
...
 		Expect(err).To(BeNil())
 
 		twoChanges := []byte("second version")
-		err = afs.WriteFile(twoPath, twoChanges, os.ModePerm)
+		err = afs.WriteFile(twoPath, twoChanges, core.DefaultFileMode)
 		Expect(err).To(BeNil())
 
 		headerContents := []byte("a simple header\n")
-		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:113]:
```suggestion
		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 13]
```diff
@@ -103,15 +102,15 @@ first version`
 		twoPath := filepath.Join("news", "v0.2.0.md")
 
 		oneChanges := []byte("first version")
-		err := afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err := afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
 		Expect(err).To(BeNil())
 
 		twoChanges := []byte("second version")
-		err = afs.WriteFile(twoPath, twoChanges, os.ModePerm)
+		err = afs.WriteFile(twoPath, twoChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:109]:
```suggestion
		err = afs.WriteFile(twoPath, twoChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 14]
```diff
@@ -103,15 +102,15 @@ first version`
 		twoPath := filepath.Join("news", "v0.2.0.md")
 
 		oneChanges := []byte("first version")
-		err := afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err := afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:105]:
```suggestion
		err := afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 15]
```diff
@@ -79,7 +78,7 @@ var _ = Describe("Merge", func() {
   "key": "value",
   "version": "0.2.0",
 }`
-		err = afs.WriteFile("replace.json", []byte(jsonContents), os.ModePerm)
+		err = afs.WriteFile("replace.json", []byte(jsonContents), core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:81]:
```suggestion
		err = afs.WriteFile("replace.json", []byte(jsonContents), core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 16]
```diff
@@ -57,15 +56,15 @@ var _ = Describe("Merge", func() {
...
 		Expect(err).To(BeNil())
 
 		twoChanges := []byte("second version")
-		err = afs.WriteFile(twoPath, twoChanges, os.ModePerm)
+		err = afs.WriteFile(twoPath, twoChanges, core.DefaultFileMode)
 		Expect(err).To(BeNil())
 
 		headerContents := []byte("a simple header\n")
-		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, os.ModePerm)
+		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:67]:
```suggestion
		err = afs.WriteFile(filepath.Join("news", "header.rst"), headerContents, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 17]
```diff
@@ -57,15 +56,15 @@ var _ = Describe("Merge", func() {
 		twoPath := filepath.Join("news", "v0.2.0.md")
 
 		oneChanges := []byte("first version")
-		err := afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err := afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
 		Expect(err).To(BeNil())
 
 		twoChanges := []byte("second version")
-		err = afs.WriteFile(twoPath, twoChanges, os.ModePerm)
+		err = afs.WriteFile(twoPath, twoChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:63]:
```suggestion
		err = afs.WriteFile(twoPath, twoChanges, core.CreateFileMode)
```

File: cmd/merge_test.go [hunk 18]
```diff
@@ -57,15 +56,15 @@ var _ = Describe("Merge", func() {
 		twoPath := filepath.Join("news", "v0.2.0.md")
 
 		oneChanges := []byte("first version")
-		err := afs.WriteFile(onePath, oneChanges, os.ModePerm)
+		err := afs.WriteFile(onePath, oneChanges, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/merge_test.go:59]:
```suggestion
		err := afs.WriteFile(onePath, oneChanges, core.CreateFileMode)
```

File: cmd/init.go [hunk 19]
```diff
@@ -83,22 +82,22 @@ func initPipeline(mkdir shared.MkdirAller, wf shared.WriteFiler, config core.Con
...
 	}
 
-	err = wf(headerPath, []byte(defaultHeader), os.ModePerm)
+	err = wf(headerPath, []byte(defaultHeader), core.DefaultFileMode)
 	if err != nil {
 		return err
 	}
 
-	err = wf(config.ChangelogPath, []byte(defaultChangelog), os.ModePerm)
+	err = wf(config.ChangelogPath, []byte(defaultChangelog), core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/init.go:100]:
```suggestion
	err = wf(config.ChangelogPath, []byte(defaultChangelog), core.CreateFileMode)
```

File: cmd/init.go [hunk 20]
```diff
@@ -83,22 +82,22 @@ func initPipeline(mkdir shared.MkdirAller, wf shared.WriteFiler, config core.Con
...
 	}
 
-	err = wf(keepPath, []byte{}, os.ModePerm)
+	err = wf(keepPath, []byte{}, core.DefaultFileMode)
 	if err != nil {
 		return err
 	}
 
-	err = wf(headerPath, []byte(defaultHeader), os.ModePerm)
+	err = wf(headerPath, []byte(defaultHeader), core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/init.go:95]:
```suggestion
	err = wf(headerPath, []byte(defaultHeader), core.CreateFileMode)
```

File: cmd/init.go [hunk 21]
```diff
@@ -83,22 +82,22 @@ func initPipeline(mkdir shared.MkdirAller, wf shared.WriteFiler, config core.Con
...
 	}
 
-	err = mkdir(unreleasedPath, 0755)
+	err = mkdir(unreleasedPath, core.DefaultDirMode)
 	if err != nil {
 		return err
 	}
 
-	err = wf(keepPath, []byte{}, os.ModePerm)
+	err = wf(keepPath, []byte{}, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/init.go:90]:
```suggestion
	err = wf(keepPath, []byte{}, core.CreateFileMode)
```

File: cmd/init.go [hunk 22]
```diff
@@ -83,22 +82,22 @@ func initPipeline(mkdir shared.MkdirAller, wf shared.WriteFiler, config core.Con
 		return err
 	}
 
-	err = mkdir(unreleasedPath, 0755)
+	err = mkdir(unreleasedPath, core.DefaultDirMode)
```
Comment (miniscruff) [inline cmd/init.go:85]:
```suggestion
	err = mkdir(unreleasedPath, core.CreateDirMode)
```

File: cmd/e2e_test.go [hunk 23]
```diff
@@ -168,7 +170,7 @@ time: %s`, date)
 
 	testGen := func() {
 		docsPath := filepath.Join(tempDir, "website", "content", "cli")
-		Expect(os.MkdirAll(docsPath, os.ModePerm)).To(Succeed())
+		Expect(os.MkdirAll(docsPath, core.DefaultDirMode)).To(Succeed())
```
Comment (miniscruff) [inline cmd/e2e_test.go:173]:
```suggestion
		Expect(os.MkdirAll(docsPath, core.CreateDirMode)).To(Succeed())
```

File: cmd/batch_test.go [hunk 24]
```diff
@@ -532,7 +532,7 @@ second footer
 
 	It("returns err if bad changes file", func() {
 		badYaml := []byte("not a valid yaml:::::file---___")
-		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), badYaml, os.ModePerm)
+		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), badYaml, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/batch_test.go:535]:
```suggestion
		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), badYaml, core.CreateFileMode)
```

File: cmd/batch_test.go [hunk 25]
```diff
@@ -510,7 +510,7 @@ second footer
 		})
 
 		ignoredPath := filepath.Join(futurePath, "ignored.txt")
-		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), os.ModePerm)).To(Succeed())
+		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), core.DefaultFileMode)).To(Succeed())
```
Comment (miniscruff) [inline cmd/batch_test.go:513]:
```suggestion
		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), core.CreateFileMode)).To(Succeed())
```

File: cmd/batch_test.go [hunk 26]
```diff
@@ -480,7 +480,7 @@ second footer
 		writeChangeFile(core.Change{Kind: "added", Body: "second", Time: orderedTimes[1]})
 
 		ignoredPath := filepath.Join(futurePath, "ignored.txt")
-		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), os.ModePerm)).To(Succeed())
+		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), core.DefaultFileMode)).To(Succeed())
```
Comment (miniscruff) [inline cmd/batch_test.go:483]:
```suggestion
		Expect(afs.WriteFile(ignoredPath, []byte("ignored"), core.CreateFileMode)).To(Succeed())
```

File: cmd/batch_test.go [hunk 27]
```diff
@@ -342,7 +342,7 @@ second footer
 		}
 
 		aVer := []byte("not a valid change")
-		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), aVer, os.ModePerm)
+		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), aVer, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/batch_test.go:345]:
```suggestion
		err := afs.WriteFile(filepath.Join(futurePath, "a.yaml"), aVer, core.CreateFileMode)
```

File: cmd/batch_test.go [hunk 28]
```diff
@@ -327,7 +327,7 @@ second footer
 
 	It("returns error on bad config", func() {
 		configData := []byte("not a proper config")
-		err := afs.WriteFile(core.ConfigPaths[0], configData, os.ModePerm)
+		err := afs.WriteFile(core.ConfigPaths[0], configData, core.DefaultFileMode)
```
Comment (miniscruff) [inline cmd/batch_test.go:330]:
```suggestion
		err := afs.WriteFile(core.ConfigPaths[0], configData, core.CreateFileMode)
```

File: cmd/batch_test.go [hunk 29]
```diff
@@ -155,13 +155,13 @@ var _ = Describe("Batch", func() {
...
 
-		Expect(afs.WriteFile(filePath, bs, os.ModePerm)).To(Succeed())
+		Expect(afs.WriteFile(filePath, bs, core.DefaultFileMode)).To(Succeed())
 	}
 
 	writeFutureFile := func(header, configPath string) {
 		headerData := []byte(header)
 		headerPath := filepath.Join(futurePath, configPath)
-		Expect(afs.WriteFile(headerPath, headerData, os.ModePerm)).To(Succeed())
+		Expect(afs.WriteFile(headerPath, headerData, core.DefaultFileMode)).To(Succeed())
```
Comment (miniscruff) [inline cmd/batch_test.go:164]:
```suggestion
		Expect(afs.WriteFile(headerPath, headerData, core.CreateFileMode)).To(Succeed())
```

File: cmd/batch_test.go [hunk 30]
```diff
@@ -155,13 +155,13 @@ var _ = Describe("Batch", func() {
 			strings.Join(nameParts, "-"),
 		)
 
-		Expect(afs.WriteFile(filePath, bs, os.ModePerm)).To(Succeed())
+		Expect(afs.WriteFile(filePath, bs, core.DefaultFileMode)).To(Succeed())
```
Comment (miniscruff) [inline cmd/batch_test.go:158]:
```suggestion
		Expect(afs.WriteFile(filePath, bs, core.CreateFileMode)).To(Succeed())
```

**Review by miniscruff — CHANGES_REQUESTED** [review]
Need to update usage after the variable changed.

**Review by miniscruff — APPROVED** [review]
